Host: :8080
Meta: couchbase://scpodb01:8091/default
BucketMeta: couchbase://scpodb01:8091/buckets
Storage:
  Cluster:
    - 127.0.0.1:9001
    - 127.0.0.1:9002
    - 127.0.0.1:9003
Log:
  Home: logs
  Level: debug