Host: 0.0.0.0:8089
LegacyFS:
Meta: http://whalefs:123456@10.59.75.71:8091/whalefs
BucketMeta: http://whalefs:123456@10.59.75.71:8091/basis
ChunkMeta: http://whalefs:123456@10.59.75.71:8091/chunks
TaskBucket: http://whalefs:123456@10.59.75.71:8091/tasks
TaskFileBucketName: benjamin
TaskFileSizeThreshold: 1073741824
HttpClientBase: http://localhost:8089
JwtSecretKey: 093d0f9c0e1507950b3922ba634e2faeea8f5d44
TempFileDir: ./tmp/
Basis:
  BucketHome: home
  CollectionTmp: tmp
  CollectionTmpReplication: 000
  CollectionTmpTTL: 7d
  CollectionShare: mass
  CollectionShareReplication: 100
  SizeDefault: p200
Storage:
  Type: fs
  OSS:
    EndPoint: https://oss-cn-chengdu.aliyuncs.com
    AccessKeyID: x
    AccessKeySecret: x
  Cluster:
    - 10.59.75.71:9333
Log:
  Home: logs
  Level: debug
Sync:
  Enable: false
  DFSHost: http://localhost:8089
  RabbitMQConnection: amqp://guest:guest@localhost:5672/dfs
  RabbitMQExchange: /whale-fs
  RabbitMQQueue: whale-fs
  LegacyFSRoot: /Users/benjamin.c.yan/dfs/legacyfs
Portal:
  dfsHost: http://oss.st.anhouse.com.cn
