Host: :8089
Meta: http://whalefs:123456@192.168.1.9:8091/whalefs
MetaPassword: 123456
BucketMeta: http://whalefs:123456@192.168.1.9:8091/whalefs
BucketMetaPassword: 123456
TaskBucket: http://whalefs:123456@192.168.1.9:8091/tasks
TaskFileBucketName: benjamin
TaskFileSizeThreshold: 1024
Storage:
  Cluster:
    - 192.168.1.9:9333
Log:
  Home: logs
  Level: debug