Host: :8089
Meta: couchbase://whalefs:123456@10.211.55.4:8091/whalefs
BucketMeta: couchbase://whalefs:123456@10.211.55.4:8091/whalefs
Storage:
  Cluster:
    - 127.0.0.1:9333
Log:
  Home: logs
  Level: debug