Host: ":8080"
DFISUpload: "http://10.16.78.84"
DFISDownload: "http://10.16.78.84"
DFISGroup: "benjamin/test"
LogHome: "logs"
LogLevel: "error"
EngineApi: "http://st01nbx01/engine_api"
BodyLimit: "20M"
OverlayDefaultStyle: "Times New Roman_40"
CacheMaxAge: "300"
NegApi: "http://10.16.75.24:3000"
TransformMessageName: "DFIS_Transform_Statistic"