Host: :8080
Meta: couchbase://localhost:8091/default
BucketMeta: couchbase://localhost:8091/buckets
Storage:
  Master:
    - 127.0.0.1:9001
    - 127.0.0.1:9002
Log:
  Home: logs
  Level: debug