Host: :8089
LegacyFS: https://file.yzw.cn
Meta: http://whale:3vxtMJHTI!IDRGrW@192.168.220.65:8091/whalefs
BucketMeta: http://whale:3vxtMJHTI!IDRGrW@192.168.220.65:8091/basis
ChunkMeta: http://whale:3vxtMJHTI!IDRGrW@192.168.220.65:8091/chunks
TaskBucket: http://whale:3vxtMJHTI!IDRGrW@192.168.220.65:8091/tasks
TaskFileBucketName: benjamin
TaskFileSizeThreshold: 1073741824
HttpClientBase: http://localhost:8089
TempFileDir: ./tmp/
Basis:
  BucketHome: home
  CollectionTmp: tmp
  CollectionTmpReplication: 000
  CollectionTmpTTL: 7d
  CollectionShare: mass
  CollectionShareReplication: 100
  SizeDefault: p200
Storage:
  Cluster:
    - 192.168.220.65:9333
    - 192.168.220.65:9334
    - 192.168.220.66:9333
Log:
  Home: logs
  Level: warning
Sync:
  Enable: true
  DFSHost: https://oss.yzw.cn
  RabbitMQConnection: amqp://ifs_admin:ifs@123@192.168.110.81:5672/framework
  RabbitMQExchange: /whale-fs
  RabbitMQQueue: whale-fs
  LegacyFSRoot: F:\image
Portal:
  dfsHost: http://192.