Host: :8089
LegacyFS:
Meta: http://whale:mall@PINGANUT@shc-zc-dfs001:8091/whalefs
BucketMeta: http://whale:mall@PINGANUT@shc-zc-dfs001:8091/basis
ChunkMeta: http://whale:mall@PINGANUT@shc-zc-dfs001:8091/chunks
TaskBucket: http://whale:mall@PINGANUT@shc-zc-dfs001:8091/tasks
TaskFileBucketName: test
TaskFileSizeThreshold: 1073741824
HttpClientBase: http://localhost:8089
JwtSecretKey: 22858338a7ecf809d4a493ead5bbaea2db043847
TempFileDir: ./tmp/
Basis:
  BucketHome: home
  CollectionTmp: tmp
  CollectionTmpReplication: 000
  CollectionTmpTTL: 7d
  CollectionShare: mass
  CollectionShareReplication: 100
  SizeDefault: Original
Storage:
  Cluster:
    - shc-zc-dfs001:9333
    - shc-zc-dfs002:9333
    - shc-zc-dfs003:9333
Log:
  Home: logs
  Level: warning
Sync:
  Enable: false
  DFSHost: https://oss.yzw.cn
  RabbitMQConnection: amqp://ifs_admin:ifs@123@192.168.110.81:5672/framework
  RabbitMQExchange: /whale-fs
  RabbitMQQueue: whale-fs
  LegacyFSRoot: F:\image
Portal:
  dfsHost: https://oss.pinganut.com