Host: ":8080"
DFISUpload: "http://neg-app-dfis-c4"
DFISDownload: "http://neg-app-img"
DFISGroup: "engine/file"
LogHome: "logs"
LogLevel: "error"
EngineApi: "http://neg-app-dfis-tool/engine_api"
BodyLimit: "20M"
OverlayDefaultStyle: "Times New Roman_40"
CacheMaxAge: "300"
NegApi: "http://apis.newegg.org"
TransformMessageName: "DFIS_Transform_Statistic"