Host: :48081
LegacyFS: 
Meta: http://whalefs:123456@10.59.75.71:8091/whalefs
BucketMeta: http://whalefs:123456@10.59.75.71:8091/basis
ChunkMeta: http://whalefs:123456@10.59.75.71:8091/chunks
TaskBucket: http://whalefs:123456@10.59.75.71:8091/tasks
TaskFileBucketName: benjamin
TaskFileSizeThreshold: 1073741824
HttpClientBase: http://localhost:8089
JwtSecretKey: ffa89d361e93f5f7f1f16c7b182a7ef5c0e48915
TempFileDir: ./tmp/
Basis:
  BucketHome: home
  CollectionTmp: tmp
  CollectionTmpReplication: 000
  CollectionTmpTTL: 7d
  CollectionShare: mass
  CollectionShareReplication: 100
  SizeDefault: Original
Storage:
  Type: fs
  Cluster:
    - 10.59.75.71:9333
Log:
  Home: logs
  Level: debug
Sync:
  Enable: false
  DFSHost: 192.168.1.9:8089
  RabbitMQConnection: amqp://admin:admin@172.16.0.131:5672//blockchain
  RabbitMQExchange: /whale-fs
  RabbitMQQueue: whale-fs
  LegacyFSRoot: D:\application\ImageServer
Portal:
  dfsHost: http://oss.st.anhouse.com.cn